# Generated by Django 5.2 on 2025-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
